name: Build and Deploy to Azure K8s

on: 
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  buildImage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.0.0

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          # Container registry username
          username: 
          # Container registry password
          password: 
          # Container registry server url
          login-server:

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.0.0
        with:
          push: true
          tags: 
          file: ./Dockerfile

  deployAzure:
    permissions:
      actions: read
      contents: read
      id-token: write

    runs-on: ubuntu-latest
    environment: Production
    needs: [buildImage]

  steps:
    - users: actions/checkout@v4.0.0

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CREDENTIALS }}
        tenant-id: 
        subscription-id:

    - name: Kube login
      uses: azure/yuser-kubelogin@v1
      with: 
        kubelogin-version: 'v0.0.25'

    - name: Kubernetes Set Context
      uses: Azure/k8s-set-context@v3.0
      with:
        resource-group:
        cluster-name:
        admin: 'false'
        use-kubelogin: 'true'

    - name: Deploy to Kubernetes culster
      uses: Azure/k8s-deploy@v4.9
      with:
        action: deploy
        manifest: 
          kubernetes/hello-world-deployment.yaml
          kubernetes/hello-world-service.yaml
        images:
        
